apiVersion: apps/v1
kind: Deployment
metadata:
  name: detection-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: detection-api
  template:
    metadata:
      labels:
        app: detection-api
    spec:
      containers:
        - name: detection-api
          image: your-dockerhub/detection-api:latest
          ports:
            - containerPort: 5000
